config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'

  resources :groups, except: %i[index show destroy] do
    scope module: :groups do
      resources :messages, only: %i[index create]
    end
  end

  resources :users, only: [] do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  delegate :name, to: :user, prefix: true

  belongs_to :group
  belongs_to :user

  validates :body, presence: true, unless: 'image.present?'

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  scope :not_user, -> (user){where.not(id: user)}
  scope :incremental_search, ->(keyword) { where('name like ?', "#{keyword}%") }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/groups/messages_controller.rb
class Groups::MessagesController < ApplicationController

  before_action :set_group, :set_messages, only: %i[index create]

  def index
    @message = Message.new

    respond_to do |format|
      format.html
      format.json do
        @messages = @group.messages.where('id > ?', params[:last_id]).includes(:user)
      end
    end
  end

  def create
    @message = current_user.messages.new(message_params)

    if @message.save
      respond_to do |format|
        format.json { render status: :created }
      end
    else
      respond_to do |format|
        format.json { render status: :internal_server_error }
      end
    end
  end

  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id])
  end

  def set_group
    @groups = current_user.groups
    @group  = @groups.find(params[:group_id])
  end

  def set_messages
    @messages = @group.messages.includes(:user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: %i[edit update]
  before_action :set_except_current_users, except: %i[index show destroy]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to group_messages_path(@group), notice: 'グループ作成成功'
    else
      flash.now[:alert] = 'グループ作成失敗'
      render :new
    end
  end

  def edit
    @members = @group.users.not_user(current_user)
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループ更新成功'
    else
      flash.now[:alert] = 'グループ更新失敗'
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def set_except_current_users
    @users = User.not_user(current_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json

  def search
    @users = User.not_user(current_user).incremental_search(params[:keyword])
    respond_with @users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
.chat-group-form
  %h1
    = group.form_title
  = form_for group, class: 'new_chat_group', id: 'new_chat_group' do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, placeholder: 'グループ名を入力してください', class: 'chat-group-form__input'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          = f.text_field :id, value: '', placeholder: '追加したいユーザー名を入力してください', id: 'user-search-field', class: 'chat-group-form__input'
        / - if @users.blank?
        /   追加するユーザーがいません
        / - else
        /   = f.collection_check_boxes :user_ids, @users, :id, :name
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label 'チャットメンバー', class: 'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            = f.hidden_field :user_ids, name: 'group[user_ids][]', value: current_user.id
            %p.chat-group-user__name
              = current_user.name
          = render partial: 'users/member', collection: members, locals: { f: f }
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/groups/_group.html.haml
= link_to group_messages_path(group) do
  .chat-side__group
    .chat-side__group-name
      = group.name
    .chat-side__group-message
      = group.latest_message

app/views/groups/edit.html.haml
= render partial: 'groups/form', locals: { group: @group, members: @members }

app/views/groups/messages/_message.html.haml
.chat-main__message.clearfix{data: { id: message.id }}
  .chat-main__message-name
    = message.user_name
  .chat-main__message-time
    = message.published_time
  .chat-main__message-body
    = message.body
    = image_tag message.image, class: 'chat-main__message-body-image'

app/views/groups/messages/index.html.haml
= render 'shared/side_bar'
.chat-main
  .chat-main__header
    .chat-main__header--group.clearfix
      .chat-main__header--group-name
        = @group.name
      = link_to edit_group_path(@group), class: 'chat-main__header--group-edit-btn' do
        edit
    .chat-main__header-members
      MEMBER:
      %i
        = @group.users.pluck(:name).join(' ')
  .chat-main__body
    .chat-main__body--messages-list
      = render @messages
  .chat-main__footer
    = form_for [@group, @message], html: {class: 'chat-main__footer-form'} do |f|
      .chat-main__footer-body
        = f.text_field :body, placeholder: 'type a message', class: 'message'
        = f.label :image, class: 'chat-file' do
          = f.file_field :image, class: 'image'
          %i.fa.fa-image
      = f.submit 'Send', class: 'submit'

= javascript_include_tag 'auto_reload'

app/views/groups/new.html.haml
= render partial: 'groups/form', locals: { group: @group, members: @members }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", http: { equiv: "Content-Type" } }
    %title ReviewSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'shared/flash'
    = yield

app/views/messages/index.html.haml
= render 'shared/side_bar'
.chat-main
  .chat-main__header
    .chat-main__header--group.clearfix
      .chat-main__header--group-name
        武南高校
      .chat-main__header--group-edit-btn
        edit
    .chat-main__header-members
      MEMBER:
      %i 隼人
  .chat-main__body
    .chat-main__body--messages-list
      .chat-main__message.clearfix
        .chat-main__message-name
          隼人
        .chat-main__message-time
          2016/11/03 08:32:37
        .chat-main__message-body
          えげつねえな
      .chat-main__message.clearfix
        .chat-main__message-name
          隼人
        .chat-main__message-time
          2016/11/03 08:32:37
        .chat-main__message-body
          えげつねえな
      .chat-main__message.clearfix
        .chat-main__message-name
          隼人
        .chat-main__message-time
          2016/11/03 08:32:37
        .chat-main__message-body
          えげつねえな
      .chat-main__message.clearfix
        .chat-main__message-name
          隼人
        .chat-main__message-time
          2016/11/03 08:32:37
        .chat-main__message-body
          えげつねえな
      .chat-main__message.clearfix
        .chat-main__message-name
          隼人
        .chat-main__message-time
          2016/11/03 08:32:37
        .chat-main__message-body
          えげつねえな
      .chat-main__message.clearfix
        .chat-main__message-name
          隼人
        .chat-main__message-time
          2016/11/03 08:32:37
        .chat-main__message-body
          えげつねえな
      .chat-main__message.clearfix
        .chat-main__message-name
          隼人
        .chat-main__message-time
          2016/11/03 08:32:37
        .chat-main__message-body
          えげつねえな
  .chat-main__footer
    %form.chat-main__footer-form
      .chat-main__footer-body
        %input.message{type: 'text', placeholder: 'type a message'}
        %label.chat-file
          %input.image{type: 'file'}
          %i.fa.fa-image
      %input.submit{type: 'sibmit', value: 'Send'}

app/views/shared/_flash.html.haml
.notification
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)

app/views/shared/_side_bar.html.haml
.chat-side
  .chat-side__user
    .chat-side__user-content
      .chat-side__user-name
        = current_user.name
      = link_to new_group_path, class: 'chat-side__user--new-group' do
        = fa_icon 'pencil-square-o'
      = link_to edit_user_registration_path, class: 'chat-side__user--edit-user' do
        = fa_icon 'cog'
  .chat-side__groups
    .chat-side__groups-list
      = render partial: 'groups/group', collection: @groups

app/views/users/_member.html.haml
.chat-group-user.clearfix
  = f.hidden_field :user_ids, name: 'group[user_ids][]', value: member.id
  %p.chat-group-user__name
    = member.name
  .chat-group-user__btn.chat-group-user__btn--remove
    削除